version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - tomcat
  tomcat:
    image: tomcat:latest
    deploy:
      replicas: 1
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 8080
    build: ./
    volumes:
      - ./html:/usr/local/tomcat/webapps/ROOT

      
    
